batch_demos script: spacing/variable update
marcobarilari/layer-MAP pull request #22
Opened 2024-02-28 15:08 UTC by mrneont

2025-05-12 13:08 UTC, marcobarilari commented
Hi Paul! 

As they say, better late than never. I am back at polishing this tool and this PR has lots of very good improvements. Sending a review soon.

2025-05-12 13:31 UTC, marcobarilari requested changes
Thanks a lot for this, lots of input and caught errors!

2025-05-12 13:31 UTC, marcobarilari commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
>  ## VASO PIPELINE - SEGMENTATION AND LAYERS
```suggestion
## layerfMRI-toolbox PIPELINE - STRUCTURAL TISSUE SEGMENTATION AND LAYERS DEFINITION
```

2025-05-12 13:31 UTC, marcobarilari commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
> +# ver = 1.0
let's keep it low profile and aligned with the general toolbox versionig
```suggestion
# ver = 0.1.0 beta
```

2025-05-12 13:31 UTC, marcobarilari commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
> +deriv_dir=${root_dir}/outputs/derivatives
While I like the abbreviation from `layerfMRI` to `lfmri` (I am naming also the derivatives folders after this suggestion), I would not keep it constant over folder naming to keep them as transparent as possible. 
If a "rule" is easier to follow, I would say that naming should correspond as much as possible to reality i.e. if a folder is named 'derivatives', the variable should have the same name in it. 

 Open to discussion.

2025-05-12 13:31 UTC, marcobarilari commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
> +++ "Remove the MP2RAGE noise via presurfer"
```suggestion
echo "++ Remove the MP2RAGE noise via presurfer"
```

2025-05-12 13:31 UTC, marcobarilari commented on src/segment-layers/convert_afni_surface_to_volume_tissue_mask.sh
> +# usage: convert_surface_to_volume_tissue_mask.sh <SUMA_dir>
```suggestion
# usage: convert_surface_to_volume_tissue_mask.sh <SUMA_dir> \
```

2025-05-12 13:31 UTC, marcobarilari commented on src/segment-layers/convert_afni_surface_to_volume_tissue_mask.sh
> +echo "++ Generate RIBBON volume mask"
I like this suggestion, though the `++` is afni style and I do not want to steal it. What about `≡`?  The identitidy sign looks like 3 layers

2025-05-12 13:31 UTC, marcobarilari commented on src/segment-layers/run_freesurfer_recon_all.sh
> +\mkdir -p $output_dir
is the `\` at the beginning of the line a typo or some bah dark magic that I do not know?

2025-05-12 13:31 UTC, marcobarilari commented on src/segment-layers/run_suma_fs_to_surface.sh
> +\mv $fs_surf_path/SUMA $suma_output_dir
is the `\` at the beginning of the line a typo or some bah dark magic that I do not know?

2025-05-12 13:31 UTC, marcobarilari commented on src/segment-layers/upsample_suma_surface.sh
> +echo  "++ Dense mesh starting"
see above suggestion for `≡`

2025-05-13 17:17 UTC, mrneont commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
> +# ver = 1.0
Maybe a related concept: we have found it useful to tie the version number to a date, so that in the `major.minor.micro` numbering the `major` carries the year.  It can be fine to extend it to `major.minor.micro_beta` description, if desired.

I believe `conda` does this as well as other tools.

2025-05-13 17:26 UTC, mrneont commented on src/segment-layers/convert_afni_surface_to_volume_tissue_mask.sh
> +echo "++ Generate RIBBON volume mask"
I don't recognize that character---is it non-ascii? It would be good to probably avoid non-ascii.  I don't think "++" is copywrited...

2025-05-13 17:28 UTC, mrneont commented on src/segment-layers/run_suma_fs_to_surface.sh
> +\mv $fs_surf_path/SUMA $suma_output_dir
The `\` at the start of the command means that any aliasing will be avoided. That makes these commands more stable across systems and time.

--pt

2025-05-13 17:29 UTC, mrneont commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
It's possible I did the wrong thing here---I meant to accept your suggestion, @marcobarilari , but now i can't quite tell.  Did I commit a change in error?

2025-05-13 17:31 UTC, mrneont commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
> +deriv_dir=${root_dir}/outputs/derivatives
Sure, anything is fine.  Very long filenames get a bit onerous in a script.  Some abbreviations seem pretty straightforward to me for variable names, like `deriv` or `derivs` for `derivatives`.

2025-05-13 17:31 UTC, mrneont commented on src/segment-layers/run_freesurfer_recon_all.sh
> +\mkdir -p $output_dir
It escapes any aliasing that users might have made (see; https://github.com/marcobarilari/layerfMRI-toolbox/pull/22#discussion_r2087325401).

2025-05-20 19:40 UTC, marcobarilari commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
> +# ver = 1.0
Will keep that in mind. Thanks

2025-05-20 19:44 UTC, marcobarilari commented on batch_demos/layerfMRI_pipeline_segment-layers.sh
It is actually fine and you indeed accepted my suggestions

2025-05-20 19:47 UTC, marcobarilari commented on src/segment-layers/convert_afni_surface_to_volume_tissue_mask.sh
> +echo "++ Generate RIBBON volume mask"
I was actually worried about that, good that we catched this problem.

2025-05-20 19:48 UTC, marcobarilari commented on src/segment-layers/run_suma_fs_to_surface.sh
> +\mv $fs_surf_path/SUMA $suma_output_dir
Alright, thanks for the explanation

2025-05-20 19:49 UTC, marcobarilari commented
Thanks again, Paul. I will finally merge this PR soon unless you see any further comment/edit to add.

Cheers

2025-05-20 19:49 UTC, marcobarilari approved these changes

2025-06-10 09:37 UTC, merged